Repository RevenueCat/purchases-unity, pull requests merged in 2022-10, with the labels that each got.

#156 Update fastlane plugin
  Gemfile.lock
Labels: ci

#158 Update receivedUpdatedCustomerInfo delegate
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
Labels: fix

#160 Release/4.3.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  IntegrationTests/ProjectSettings/ProjectSettings.asset
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  VERSIONS.md
Labels: next_release

#162 fix compatibility issues with C# 7.3
  RevenueCat/Example/PurchasesListener.cs
  RevenueCat/Scripts/PurchasesConfiguration.cs
Labels: fix
