Repository RevenueCat/purchases-unity, pull requests merged in 2023-01, with the labels that each got.

#208 remove stalebot in favor of SLAs in Zendesk
  .github/stale.yml
Labels: ci

#204 add openupm badge
  README.md
Labels: docs

#209 Feature parity: subscriber attributes
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesWrapper.cs
  RevenueCat/Scripts/PurchasesWrapperAndroid.cs
  RevenueCat/Scripts/PurchasesWrapperNoop.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
  Subtester/Assets/Scripts/PurchasesListener.cs
  Subtester/Packages/manifest.json
  Subtester/Packages/packages-lock.json
Labels: feat

#210 added extra link to the correct file for symlinking sources
  Subtester/Assets/Plugins/Android/mainTemplate.gradle
Labels: test

#213 Update fastlane plugin
  Gemfile.lock
Labels: ci

#214 Adds missing params for better changelogs when bumping
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#222 Add StoreProduct.SubscriptionPeriod
  IntegrationTests/Assets/APITests/StoreProductAPITests.cs
  RevenueCat/Scripts/StoreProduct.cs
Labels: feat

#227 `.gitignore` `.vsconfig` Visual Studio files
  .gitignore
Labels: build

#231 Update gems
  Gemfile.lock
Labels: dependencies
