Repository RevenueCat/purchases-unity, pull requests merged in 2023-02, with the labels that each got.

#234 Adds dependabot
  .github/dependabot.yml
  Gemfile
Labels: ci

#226 Added `Purchases.SetLogLevel`
  IntegrationTests/Assets/APITests/LogLevelAPITests.cs
  IntegrationTests/Assets/APITests/LogLevelAPITests.cs.meta
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/Scripts/LogLevel.cs
  RevenueCat/Scripts/LogLevel.cs.meta
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesWrapper.cs
  RevenueCat/Scripts/PurchasesWrapperAndroid.cs
  RevenueCat/Scripts/PurchasesWrapperNoop.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
  Subtester/Assets/Scripts/PurchasesListener.cs
Labels: feat

#237 Adds Purchases.SetLogHandler
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/Scripts/LogLevel.cs
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesWrapper.cs
  RevenueCat/Scripts/PurchasesWrapperAndroid.cs
  RevenueCat/Scripts/PurchasesWrapperNoop.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
  Subtester/Packages/manifest.json
  Subtester/Packages/packages-lock.json
Labels: feat

#245 Fix for `NSInvalidArgumentException` in `GetPromotionalOffer`
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
Labels: fix

#249 Runs integration tests on main too
  .circleci/config.yml
Labels: test
