Repository RevenueCat/purchases-unity, pull requests merged in 2023-11, with the labels that each got.

#362 Add `3.5.4` to `VERSIONS`
  VERSIONS.md
Labels: docs

#367 `CI`: disable `prepare-next-version`
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#370 `Trusted entitlements`: Add support for trusted entitlements
  IntegrationTests/Assets/APITests/EntitlementInfoAPITests.cs
  IntegrationTests/Assets/APITests/EntitlementInfosAPITests.cs
  IntegrationTests/Assets/APITests/EntitlementVerificationModeAPITests.cs
  IntegrationTests/Assets/APITests/EntitlementVerificationModeAPITests.cs.meta
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  IntegrationTests/Assets/APITests/VerificationResultAPITests.cs
  IntegrationTests/Assets/APITests/VerificationResultAPITests.cs.meta
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/Scripts/EntitlementInfo.cs
  RevenueCat/Scripts/EntitlementInfos.cs
  RevenueCat/Scripts/EntitlementVerificationMode.cs
  RevenueCat/Scripts/EntitlementVerificationMode.cs.meta
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesConfiguration.cs
  RevenueCat/Scripts/PurchasesWrapper.cs
  RevenueCat/Scripts/PurchasesWrapperAndroid.cs
  RevenueCat/Scripts/PurchasesWrapperNoop.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
  RevenueCat/Scripts/VerificationResult.cs
  RevenueCat/Scripts/VerificationResult.cs.meta
Labels: feat

#375 Adds `isConfigured`
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesWrapper.cs
  RevenueCat/Scripts/PurchasesWrapperAndroid.cs
  RevenueCat/Scripts/PurchasesWrapperNoop.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
  Subtester/Assets/Scripts/PurchasesListener.cs
Labels: feat

#376 Fix `isAnonymous` in iOS
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
Labels: fix
