Repository RevenueCat/purchases-unity, pull requests merged in 2023-10, with the labels that each got.

#335 Add missing `IntroEligibilityStatusNoIntroOfferExists`
  IntegrationTests/Assets/APITests/IntroEligibilityStatusAPITests.cs
  RevenueCat/Scripts/IntroEligibilityStatus.cs
Labels: feat

#331 Temporarily remove DEFERRED proration mode in preparation for upgrade to Billing Client 6
  IntegrationTests/Assets/APITests/ProrationModeAPITests.cs
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  RevenueCat/Scripts/ProrationMode.cs
Labels: breaking

#338 Add support for configuring in-app messages
  IntegrationTests/Assets/APITests/InAppMessageTypeAPITests.cs
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/Scripts/InAppMessageType.cs
  RevenueCat/Scripts/InAppMessageType.cs.meta
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesConfiguration.cs
  RevenueCat/Scripts/PurchasesWrapper.cs
  RevenueCat/Scripts/PurchasesWrapperAndroid.cs
  RevenueCat/Scripts/PurchasesWrapperNoop.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
  Subtester/Assets/Scripts/PurchasesListener.cs
Labels: breaking

#339 Release/6.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/package.json
  VERSIONS.md
Labels: next_release

#342 update RELEASING file to use the latest process
  RELEASING.md
Labels: ci

#344 Update Unity IAP compatibility for v6 in VERSIONS.md
  VERSIONS.md
Labels: docs

#345 Add BillingClient versions to VERSIONS table
  VERSIONS.md
Labels: docs

#346 Remove creation of special UnityIAP package
  .circleci/config.yml
  AMAZON-INSTRUCTIONS.md
  fastlane/Fastfile
  scripts/create-unity-package.sh
Labels: docs
