Repository RevenueCat/purchases-unity, pull requests merged in 2024-08, with the labels that each got.

#485 Add support new native majors
  .circleci/config.yml
  AMAZON-INSTRUCTIONS.md
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  IntegrationTests/Assets/APITests/SubscriptionOptionAPITests.cs
  IntegrationTests/ProjectSettings/ProjectSettings.asset
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/Editor/RevenueCatDependencies.xml
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesAreCompletedBy.cs
  RevenueCat/Scripts/PurchasesAreCompletedBy.cs.meta
  RevenueCat/Scripts/PurchasesConfiguration.cs
  RevenueCat/Scripts/PurchasesWrapper.cs
  RevenueCat/Scripts/PurchasesWrapperAndroid.cs
  RevenueCat/Scripts/PurchasesWrapperNoop.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
  RevenueCat/Scripts/StoreKitVersion.cs
  RevenueCat/Scripts/StoreKitVersion.cs.meta
  RevenueCat/Scripts/SubscriptionOption.cs
  Subtester/Assets/Plugins/Android/mainTemplate.gradle
  Subtester/ProjectSettings/AndroidResolverDependencies.xml
  migrations/v7-MIGRATION.md
Labels: breaking

#489 Update Deferred proration mode value to match BC7
  RevenueCat/Scripts/ProrationMode.cs
Labels: fix

#442 `Amazon`: Add getAmazonLWAConsentStatus method to support Quick Subscribe
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesWrapper.cs
  RevenueCat/Scripts/PurchasesWrapperAndroid.cs
  RevenueCat/Scripts/PurchasesWrapperNoop.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
  Subtester/Assets/Scripts/PurchasesListener.cs
Labels: feat

#490 Release/7.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/package.json
  VERSIONS.md
Labels: next_release

#493 Add SyncPurchases method overload that accepts a callback as parameter
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/Scripts/Purchases.cs
  Subtester/Assets/Scripts/PurchasesListener.cs
Labels: feat
