Repository RevenueCat/purchases-unity, pull requests merged in 2024-09, with the labels that each got.

#498 [PurchaseTester] Add button to test the GetAmazonLWAConsentStatus method
  Subtester/Assets/Scripts/PurchasesListener.cs
Labels: refactor

#500 Update VERSIONS.md to remove compatibility with Unity IAP for BC7
  VERSIONS.md
Labels: fix

#501 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: pr:ci

#503 Update allowSharingAppStoreAccount Deprecation Message
  RevenueCat/Scripts/Purchases.cs
Labels: pr:docs

#505 Bump fastlane-plugin-revenuecat_internal from 5140dbc to 55a0455
  Gemfile.lock
Labels: pr:other
