Repository RevenueCat/purchases-unity, pull requests merged in 2024-03, with the labels that each got.

#416 Update CHANGELOG to include 5.3.2 release notes
  CHANGELOG.md
  VERSIONS.md
Labels: refactor

#433 Adds`Purchases.getCurrentOfferingForPlacement(placementID)` and `Purchases.syncAttributesAndOfferingsIfNeeded()`
  RevenueCat/Plugins/Android/PurchasesWrapper.java
  RevenueCat/Plugins/iOS/PurchasesUnityHelper.m
  RevenueCat/Scripts/Package.cs
  RevenueCat/Scripts/PresentedOfferingContext.cs
  RevenueCat/Scripts/PresentedOfferingContext.cs.meta
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesWrapper.cs
  RevenueCat/Scripts/PurchasesWrapperAndroid.cs
  RevenueCat/Scripts/PurchasesWrapperNoop.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
  RevenueCat/Scripts/StoreProduct.cs
  RevenueCat/Scripts/SubscriptionOption.cs
  Subtester/Assets/ExternalDependencyManager/Editor/1.2.176/Google.IOSResolver.dll.mdb.meta
  Subtester/Assets/ExternalDependencyManager/Editor/1.2.176/Google.IOSResolver.dll.meta
  Subtester/Assets/ExternalDependencyManager/Editor/1.2.176/Google.JarResolver.dll.mdb.meta
  Subtester/Assets/ExternalDependencyManager/Editor/1.2.176/Google.JarResolver.dll.meta
  Subtester/Assets/ExternalDependencyManager/Editor/1.2.176/Google.PackageManagerResolver.dll.mdb.meta
  Subtester/Assets/ExternalDependencyManager/Editor/1.2.176/Google.PackageManagerResolver.dll.meta
  Subtester/Assets/ExternalDependencyManager/Editor/1.2.176/Google.VersionHandlerImpl.dll.mdb.meta
  Subtester/Assets/ExternalDependencyManager/Editor/1.2.176/Google.VersionHandlerImpl.dll.meta
  Subtester/Assets/Scripts/PurchasesListener.cs
Labels: feat

#438 Fix `purchasePackage` when no targeting context
  RevenueCat/Scripts/PresentedOfferingContext.cs
Labels: fix
