Repository RevenueCat/purchases-unity, pull requests merged in 2024-07, with the labels that each got.

#475 Update Unity IAP compatiiblity
  VERSIONS.md
Labels: ci

#476 Update `VERSIONS.md` to include Billing client version and update fastlane plugin
  Gemfile.lock
  VERSIONS.md
Labels: dependencies, docs

#479 Fix `Gemfile.lock` with new fastlane plugin dependencies
  Gemfile.lock
  fastlane/README.md
Labels: refactor
