Repository RevenueCat/purchases-unity, pull requests merged in 2024-10, with the labels that each got.

#471 Add visionOS support
  RevenueCat/Editor/RevenueCatPostInstall.cs
  RevenueCat/Scripts/Purchases.cs
  RevenueCat/Scripts/PurchasesWrapperiOS.cs
Labels: pr:feat

#522 Support displaying deferred win-back StoreKit messages
  IntegrationTests/Assets/APITests/InAppMessageTypeAPITests.cs
  IntegrationTests/Assets/APITests/PurchasesAPITests.cs
  RevenueCat/Scripts/InAppMessageType.cs
  Subtester/Assets/Scripts/PurchasesListener.cs
Labels: pr:feat, feat:Win-Back Offers

#523 Fix metadata values types
  RevenueCat/Scripts/Offering.cs
Labels: pr:fix

#521 Adds docs to `StoreProduct`
  RevenueCat/Scripts/Offering.cs
  RevenueCat/Scripts/StoreProduct.cs
Labels: pr:other
